export const FETCH_WEATHER_REQUEST = "FETCH_WEATHER_REQUEST";
export const FETCH_WEATHER_SUCCESS = "FETCH_WEATHER_SUCCESS";
export const FETCH_WEATHER_FAIL = "FETCH_WEATHER_FAIL";
export const FETCH_FIND_REQUEST = "FETCH_FIND_REQUEST";
export const FETCH_FIND_SUCCESS = "FETCH_FIND_SUCCESS";
export const FETCH_FIND_FAIL = "FETCH_FIND_FAIL";
export const FETCH_CITY_NAME = "FETCH_CITY_NAME";

export const WEATHER_API = "c34071385a5dcf895fd1e89b39a43188";